services:
  postgres:
    image: postgres:13-alpine
    container_name: testfull_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/jaeger:2.6.0
    container_name: testfull_jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4318:4318"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: testfull_backend
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
      OTLP_ENDPOINT: http://jaeger:4318/v1/traces
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: testfull_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
