"""create submissions table

Revision ID: 152942e4ee01
Revises: 
Create Date: 2025-05-31 16:34:01.465105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152942e4ee01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_date'), 'submissions', ['date'], unique=False)
    op.create_index(op.f('ix_submissions_first_name'), 'submissions', ['first_name'], unique=False)
    op.create_index(op.f('ix_submissions_last_name'), 'submissions', ['last_name'], unique=False)
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.drop_index(op.f('ix_submissions_last_name'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_first_name'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_date'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
